# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fmp_proto.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'fmp_proto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66mp_proto.proto\x12\x1a\x66usion_multi_node.protocol\"\xa0\x01\n\x0b\x46MPEnvelope\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x11\n\ttarget_id\x18\x02 \x01(\t\x12\x11\n\thop_count\x18\x03 \x01(\x05\x12\x10\n\x08max_hops\x18\x04 \x01(\x05\x12\r\n\x05trace\x18\x05 \x03(\t\x12\x12\n\nmessage_id\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\x01\x12\x10\n\x08sequence\x18\x08 \x01(\x05\"u\n\nFMPControl\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x10\n\x08sequence\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\x12\x0f\n\x07\x61\x63k_seq\x18\x04 \x01(\x05\x12\x13\n\x0b\x66low_window\x18\x05 \x01(\x05\x12\x0e\n\x06reason\x18\x06 \x01(\t\"\x80\x01\n\nFMPPayload\x12\x14\n\x0cpayload_type\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x10\n\x08round_id\x18\x03 \x01(\t\x12\x14\n\x0cround_number\x18\x04 \x01(\x05\x12\x12\n\nmax_rounds\x18\x05 \x01(\x05\x12\x12\n\ncompressed\x18\x06 \x01(\x08\"\xe0\x01\n\x08\x46MPFrame\x12\x39\n\x08\x65nvelope\x18\x01 \x01(\x0b\x32\'.fusion_multi_node.protocol.FMPEnvelope\x12\x37\n\x07\x63ontrol\x18\x02 \x01(\x0b\x32&.fusion_multi_node.protocol.FMPControl\x12\x37\n\x07payload\x18\x03 \x01(\x0b\x32&.fusion_multi_node.protocol.FMPPayload\x12\x11\n\tencrypted\x18\x04 \x01(\x08\x12\x14\n\x0cpayload_json\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fmp_proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FMPENVELOPE']._serialized_start=48
  _globals['_FMPENVELOPE']._serialized_end=208
  _globals['_FMPCONTROL']._serialized_start=210
  _globals['_FMPCONTROL']._serialized_end=327
  _globals['_FMPPAYLOAD']._serialized_start=330
  _globals['_FMPPAYLOAD']._serialized_end=458
  _globals['_FMPFRAME']._serialized_start=461
  _globals['_FMPFRAME']._serialized_end=685
# @@protoc_insertion_point(module_scope)
